name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release
    - name: Calculate Hashes
      id: calc_hashes
      uses: Argannor/checksum-action@master
      with: 
        glob: "target/release/*.exe"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Checksums:
          - poe-minimizer.exe
            - sha1: ${{steps.calc_hashes.outputs.targetreleasepoeminimizerexe-sha1}}
            - sha256: ${{steps.calc_hashes.outputs.targetreleasepoeminimizerexe-sha1}}
        draft: true
        prerelease: false
